version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-backend-aws
    env_file:
      - .env
    restart: unless-stopped
    command: npm run start
    depends_on:
      - mongo_db
    networks:
      - alex-aws

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./mongo_db:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - alex-aws

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/nginx.conf.aws:/etc/nginx/conf.d/default.conf
    networks:
      - alex-aws

networks:
  alex-aws:
    driver: bridge





