version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: on-failure
    networks:
      - alex-dev

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    container_name: docker-frontend-dev
    restart: on-failure
    command: npm run start:dev
    environment:
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - alex-dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docker-backend-dev
    command: npm run start
    restart: on-failure
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongo_db
    networks:
      - alex-dev

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    volumes:
      - ./mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: on-failure
    networks:
      - alex-dev

volumes:
  mongo_db:

networks:
  alex-dev:
    driver: bridge